### ISSUE TITLE
V5: Unhandled future SocketException for HTTP/2

### ISSUE THREAD

**Issue by PNixx** [amphp/http-client#312]
I catch on logs:
```
Exception handler: Amp\Future\UnhandledFutureError, Unhandled future: Amp\Http\Client\SocketException: "The HTTP/2 connection from '172.22.254.3:36222' to '17.188.179.8:443' closed unexpectedly"; Await the Future with Future::await() before the future is destroyed or use Future::ignore() to suppress this exception. Enable assertions and set AMP_DEBUG=true in the process environment to track its origin., /project/shared/vendor/amphp/amp/src/Internal/FutureState.php:53
#0 /project/shared/vendor/amphp/http-client/src/Connection/Http2Connection.php(94): Amp\Internal\FutureState->__destruct()
#1 /project/shared/vendor/amphp/http-client/src/Connection/HttpStream.php(88): Amp\Http\Client\Connection\Http2Connection->request()
#2 /project/shared/vendor/amphp/http-client/src/Connection/ConnectionLimitingPool.php(123): Amp\Http\Client\Connection\HttpStream->request()
#3 /project/shared/vendor/amphp/http-client/src/Connection/HttpStream.php(88): Amp\Http\Client\Connection\ConnectionLimitingPool->Amp\Http\Client\Connection\{closure}()
#4 /project/shared/vendor/amphp/http-client/src/Interceptor/DecompressResponse.php(43): Amp\Http\Client\Connection\HttpStream->request()
#5 /project/shared/vendor/amphp/http-client/src/Connection/InterceptedStream.php(43): Amp\Http\Client\Interceptor\DecompressResponse->requestViaNetwork()
#6 /project/shared/vendor/amphp/http-client/src/Interceptor/ModifyRequest.php(40): Amp\Http\Client\Connection\InterceptedStream->request()
#7 /project/shared/vendor/amphp/http-client/src/Connection/InterceptedStream.php(43): Amp\Http\Client\Interceptor\ModifyRequest->requestViaNetwork()
#8 /project/shared/vendor/amphp/http-client/src/Interceptor/ModifyRequest.php(40): Amp\Http\Client\Connection\InterceptedStream->request()
#9 /project/shared/vendor/amphp/http-client/src/Connection/InterceptedStream.php(43): Amp\Http\Client\Interceptor\ModifyRequest->requestViaNetwork()
#10 /project/shared/vendor/amphp/http-client/src/PooledHttpClient.php(37): Amp\Http\Client\Connection\InterceptedStream->request()
#11 /project/shared/vendor/amphp/http-client/src/Interceptor/FollowRedirects.php(129): Amp\Http\Client\PooledHttpClient->request()
#12 /project/shared/vendor/amphp/http-client/src/InterceptedHttpClient.php(30): Amp\Http\Client\Interceptor\FollowRedirects->request()
#13 /project/shared/vendor/amphp/http-client/src/Interceptor/ModifyRequest.php(52): Amp\Http\Client\InterceptedHttpClient->request()
#14 /project/shared/vendor/amphp/http-client/src/InterceptedHttpClient.php(30): Amp\Http\Client\Interceptor\ModifyRequest->request()
#15 /project/shared/vendor/amphp/http-client/src/HttpClient.php(26): Amp\Http\Client\InterceptedHttpClient->request()
#16 /project/current/src/Core/ApnsTrait.php(88): Amp\Http\Client\HttpClient->request()
#17 /project/current/src/Core/ApnsMobileSender.php(94): MyProject\Bulk\Core\ApnsMobileSender->request()
#18 /project/current/src/Model/MobilePushToken.php(92): MyProject\Bulk\Core\ApnsMobileSender->send()
#19 /project/current/src/Core/Impl/WebPush.php(150): MyProject\Bulk\Model\MobilePushToken->send()
#20 /project/current/src/Core/AbstractChannel.php(173): MyProject\Bulk\Core\Impl\WebPush->doSend()
#21 /project/current/src/Core/Launcher.php(531): MyProject\Bulk\Core\AbstractChannel->send()
#22 /project/current/src/Core/Launcher.php(354): MyProject\Bulk\Core\Launcher::sendMessage()
#23 /project/current/src/Worker/BulkWorker.php(258): MyProject\Bulk\Core\Launcher::onMessage()
#24 /project/shared/vendor/phpinnacle/ridge/src/Consumer.php(41): MyProject\Bulk\Worker\BulkWorker->onMessage()
#25 /project/shared/vendor/amphp/amp/src/functions.php(34): PHPinnacle\Ridge\Consumer->PHPinnacle\Ridge\{closure}()
#26 /project/shared/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(406): Amp\{closure}()
#27 /project/shared/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(596): Revolt\EventLoop\Internal\AbstractDriver->invokeMicrotasks()
#28 [internal function]: Revolt\EventLoop\Internal\AbstractDriver->Revolt\EventLoop\Internal\{closure}()
#29 /project/shared/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(406): Fiber->throw()
#30 /project/shared/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(596): Revolt\EventLoop\Internal\AbstractDriver->invokeMicrotasks()
#31 [internal function]: Revolt\EventLoop\Internal\AbstractDriver->Revolt\EventLoop\Internal\{closure}()
#32 /project/shared/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(478): Fiber->resume()
#33 /project/shared/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(533): Revolt\EventLoop\Internal\AbstractDriver->invokeCallbacks()
#34 [internal function]: Revolt\EventLoop\Internal\AbstractDriver->Revolt\EventLoop\Internal\{closure}()
#35 /project/shared/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(105): Fiber->resume()
#36 /project/shared/vendor/revolt/event-loop/src/EventLoop/Driver/EventDriver.php(119): Revolt\EventLoop\Internal\AbstractDriver->run()
#37 /project/shared/vendor/revolt/event-loop/src/EventLoop.php(406): Revolt\EventLoop\Driver\EventDriver->run()
#38 /project/shared/vendor/mylib/core/src/Event/Amp.php(124): Revolt\EventLoop::run()
```

Example code:
```php
try {
  $response = $this->buildClient()->request($request, new CompositeCancellation(new TimeoutCancellation(5), $cancellation));
  ...
} catch (SocketException|TimeoutException|UnprocessedRequestException|UnhandledFutureError $e) {
  ...
} catch (\Throwable $e) {
  ...
}
```

But I catch this error in only:

```php
EventLoop::setErrorHandler(function(\Throwable $e): void {
  switch(get_class($e)) {
    case UnhandledFutureError::class:
      // caught here
    break;
  }
});
```

**Comment by kelunik** [comment]
There's no future involved in `#0 /project/shared/vendor/amphp/http-client/src/Connection/Http2Connection.php(94): Amp\Internal\FutureState->__destruct()`, it's awaited in `#10 /Users/kelunik/PHP/amphp/http-client/src/Connection/Internal/Http2ConnectionProcessor.php(1052): Amp\Future->await()`. I have no idea how that stack trace is supposed to be possible. I'm therefore closing the issue. If you have a reproduction script, please respond, so we can reopen the issue.
