### ISSUE TITLE
5.x: Undefined array key 1689, Http2ConnectionProcessor.php:1316

### ISSUE THREAD

**Issue by PNixx** [amphp/http-client#325]
I catch in `EventLoop::setErrorHandler` this error.

**Comment by kelunik** [comment]
Could you please also post the stack trace?

**Comment by PNixx** [comment]
```
#0 /project/shared/vendor/amphp/http-client/src/Connection/Internal/Http2ConnectionProcessor.php(1316): Project\Worker\AbstractWorker->errorHandler()
#1 /project/shared/vendor/amphp/http-client/src/Connection/Internal/Http2ConnectionProcessor.php(1569): Amp\Http\Client\Connection\Internal\Http2ConnectionProcessor->releaseStream()
#2 /project/shared/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(577): Amp\Http\Client\Connection\Internal\Http2ConnectionProcessor->Amp\Http\Client\Connection\Internal\{closure}()
#3 [internal function]: Revolt\EventLoop\Internal\AbstractDriver->Revolt\EventLoop\Internal\{closure}()
#4 /project/shared/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(478): Fiber->resume()
#5 /project/shared/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(533): Revolt\EventLoop\Internal\AbstractDriver->invokeCallbacks()
#6 [internal function]: Revolt\EventLoop\Internal\AbstractDriver->Revolt\EventLoop\Internal\{closure}()
#7 /project/shared/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(105): Fiber->resume()
#8 /project/shared/vendor/revolt/event-loop/src/EventLoop/Driver/EventDriver.php(119): Revolt\EventLoop\Internal\AbstractDriver->run()

```

**Comment by kelunik** [comment]
Is this something you can reliably reproduce? Does https://github.com/amphp/http-client/commit/994b29fe2593f4c08733921f2f2066b0b1eb61f0 fix it?

**Comment by PNixx** [comment]
I need time to check it out

**Comment by kelunik** [comment]
I'll close it then. If the problem appears again, please comment.
