### ISSUE TITLE
[v5.0.0 Beta 15] Invalid request phase transition from Rejected to Failed

### ISSUE THREAD

**Issue by PNixx** [amphp/http-client#351]
Trace:
```
#0 vendor/amphp/http-client/src/functions.php(32): Amp\Http\Client\Internal\EventInvoker->requestFailed()
#1 vendor/amphp/http-client/src/PooledHttpClient.php(37): Amp\Http\Client\processRequest()
#2 vendor/amphp/http-client/src/Interceptor/FollowRedirects.php(153): Amp\Http\Client\PooledHttpClient->request()
#3 vendor/amphp/http-client/src/Interceptor/FollowRedirects.php(133): Amp\Http\Client\Interceptor\FollowRedirects->followRedirects()
#4 vendor/amphp/http-client/src/InterceptedHttpClient.php(44): Amp\Http\Client\Interceptor\FollowRedirects->request()
#5 vendor/amphp/http-client/src/functions.php(20): Amp\Http\Client\InterceptedHttpClient->Amp\Http\Client\{closure}()
#6 vendor/amphp/http-client/src/InterceptedHttpClient.php(49): Amp\Http\Client\processRequest()
#7 vendor/amphp/http-client/src/Interceptor/ModifyRequest.php(52): Amp\Http\Client\InterceptedHttpClient->request()
#8 vendor/amphp/http-client/src/InterceptedHttpClient.php(44): Amp\Http\Client\Interceptor\ModifyRequest->request()
#9 vendor/amphp/http-client/src/functions.php(20): Amp\Http\Client\InterceptedHttpClient->Amp\Http\Client\{closure}()
#10 vendor/amphp/http-client/src/InterceptedHttpClient.php(49): Amp\Http\Client\processRequest()
#11 vendor/amphp/http-client/src/HttpClient.php(35): Amp\Http\Client\InterceptedHttpClient->request()
#12 vendor/amphp/http-client/src/functions.php(30): Amp\Http\Client\HttpClient->Amp\Http\Client\{closure}()
#13 vendor/amphp/http-client/src/HttpClient.php(36): Amp\Http\Client\processRequest()
#14 src/Processor.php(222): Amp\Http\Client\HttpClient->request()
```

**Comment by kelunik** [comment]
Thank you! I've just released https://github.com/amphp/http-client/releases/tag/v5.0.0-beta.16 with a fix.
