### ISSUE TITLE
Received GOAWAY frame on '*.*.*.*:57656' from '*.*.*.*:443' with error code 0 and message '' 

### ISSUE THREAD

**Issue by mtalaeii** [amphp/http-client#366]
**Problem**
- I have this error on my madelineproto projects too many times and i dont have idea where its come from.
- There is no network problem with my server so i can't find why this error happen

**Trace**
- This is my full trace i received from madelineproto :

```bash
Surfaced: Amp\Http\Client\SocketException: Received GOAWAY frame on '*.*.*.*:57656' from '*.*.*.*:443' with error code 0 and message '' in /root/cat/vendor/amphp/http-client/src/Connection/Internal/Http2ConnectionProcessor.php:202
Stack trace:
#0 /root/cat/vendor/amphp/http/src/Http2/Http2Parser.php(586): Amp\Http\Client\Connection\Internal\Http2ConnectionProcessor->handleShutdown()
#1 /root/cat/vendor/amphp/http/src/Http2/Http2Parser.php(224): Amp\Http\Http2\Http2Parser->parseGoAway()
#2 [internal function]: Amp\Http\Http2\Http2Parser->parse()
#3 /root/cat/vendor/amphp/parser/src/Parser.php(113): Generator->send()
#4 /root/cat/vendor/amphp/http/src/Http2/Http2Parser.php(169): Amp\Parser\Parser->push()
#5 /root/cat/vendor/amphp/http-client/src/Connection/Internal/Http2ConnectionProcessor.php(1119): Amp\Http\Http2\Http2Parser->push()
#6 /root/cat/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(425): Amp\Http\Client\Connection\Internal\Http2ConnectionProcessor->runReadFiber()
#7 /root/cat/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(616): Revolt\EventLoop\Internal\AbstractDriver->invokeMicrotasks()
#8 [internal function]: Revolt\EventLoop\Internal\AbstractDriver->Revolt\EventLoop\Internal\{closure}()
#9 /root/cat/vendor/revolt/event-loop/src/EventLoop/Internal/DriverSuspension.php(64): Fiber->resume()
#10 /root/cat/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(425): Revolt\EventLoop\Internal\DriverSuspension::Revolt\EventLoop\Internal\{closure}()
#11 /root/cat/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(616): Revolt\EventLoop\Internal\AbstractDriver->invokeMicrotasks()
#12 [internal function]: Revolt\EventLoop\Internal\AbstractDriver->Revolt\EventLoop\Internal\{closure}()
#13 /root/cat/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(497): Fiber->resume()
#14 /root/cat/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(553): Revolt\EventLoop\Internal\AbstractDriver->invokeCallbacks()
#15 [internal function]: Revolt\EventLoop\Internal\AbstractDriver->Revolt\EventLoop\Internal\{closure}()
#16 /root/cat/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(94): Fiber->resume()
#17 /root/cat/vendor/revolt/event-loop/src/EventLoop/Internal/DriverSuspension.php(117): Revolt\EventLoop\Internal\AbstractDriver->Revolt\EventLoop\Internal\{closure}()
#18 /root/cat/vendor/amphp/amp/src/Future.php(251): Revolt\EventLoop\Internal\DriverSuspension->suspend()
#19 /root/cat/vendor/danog/madelineproto/src/Wrappers/Loop.php(108): Amp\Future->await()
#20 /root/cat/vendor/danog/madelineproto/src/AbstractAPI.php(84): danog\MadelineProto\MTProto->loop()
#21 /root/cat/vendor/danog/madelineproto/src/AbstractAPI.php(65): danog\MadelineProto\AbstractAPI->startAndLoopLogic()
#22 /root/cat/vendor/danog/madelineproto/src/EventHandler.php(167): danog\MadelineProto\AbstractAPI->startAndLoopInternal()
#23 /root/cat/bot.php(60): danog\MadelineProto\EventHandler::startAndLoopBot()
#24 {main}```

**Comment by trowski** [comment]
Fixed in `5.2.0`.
